apiVersion: v1
kind: Template
metadata:
  name: content-sources-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: content-sources
    spec:
      envName: ${ENV_NAME}
      title: ContentSources
      deploymentRepo: https://github.com/content-services/content-sources-frontend
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/content-sources
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - appId: "content-sources"
          title: "Repositories"
          href: "/insights/content/repositories"
          product: "Content"
        - appId: "content-sources"
          title: "Templates"
          href: "/insights/content/templates"
          product: "Content"
      module:
        manifestLocation: "/apps/content-sources/fed-mods.json"
        modules:
          - id: "insights-content-sources"
            module: "./RootApp"
            routes:
              - pathname: /insights/content

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/content-sources-frontend
